version: '3.5'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - ./init/firstsql.txt:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root

  postgres:
    image: postgres:9.6
    ports:
      - 15432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
