version: '3.5'
services:
  light-house:
    image: registry.webnori.com/javalabs-lighthouse:dev        
    ports:
      - "8081:8080"    
    environment:      
      TZ: Asia/Seoul
      akka.role: seed
      akka.seed: akka://ClusterSystem@light-house:12000
      akka.hostname: light-house
      akka.hostport: 12000
      akka.cluster-config: cluster.conf
    networks:
      - mynet      
  app1:
    image: registry.webnori.com/javalabs-api:dev        
    ports:
      - "8082:8080"
    depends_on:
      - light-house     
    environment:      
      TZ: Asia/Seoul
      akka.role: work
      akka.seed: akka://ClusterSystem@light-house:12000
      akka.hostname: app1
      akka.hostport: 12000
      akka.cluster-config: cluster.conf
    networks:
      - mynet
  app2:
    image: registry.webnori.com/javalabs-api:dev        
    ports:
      - "8083:8080"
    depends_on:
      - light-house     
    environment:      
      TZ: Asia/Seoul
      akka.role: work
      akka.seed: akka://ClusterSystem@light-house:12000
      akka.hostname: app2
      akka.hostport: 12000
      akka.cluster-config: cluster.conf
    networks:
      - mynet             
networks:
  mynet:
    driver: bridge



